apiVersion: apps/v1
kind: Deployment
metadata:
  name: ads-tracker
  labels:
    app: ads-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ads-tracker
  template:
    metadata:
      labels:
        app: ads-tracker
    spec:
      containers:
      - name: ads-tracker
        image: ratheeshku/ads-metric-tracker:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_HOST
          value: "0.0.0.0"
        - name: HTTP_PORT
          value: "8080"
        - name: POSTGRES_HOST
          value: "postgres-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "adsuser"
        - name: POSTGRES_PASSWORD
          value: "adspassword"
        - name: POSTGRES_DB
          value: "adsmetrics"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: NATS_URL
          value: "nats://nats-service:4222"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ads-tracker-service
  labels:
    app: ads-tracker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ads-tracker
